language: python
python:

  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run tests/test.py test
after_success:
  coveralls
